version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Packaging CloudFormation templates..."
      - |
        aws cloudformation package \
          --template-file infra/main.yaml \
          --s3-bucket ${ARTIFACTS_BUCKET} \
          --s3-prefix "cloudformation-templates" \
          --output-template-file packaged-main.yaml
artifacts:
  files:
    - packaged-main.yaml
