AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Roles and Policies for the Crypto Trading System. StackName: crypto-trading-iam'

Parameters:
  ProjectName:
    Type: String
    Default: 'CryptoTradingSystem'
    Description: 'A prefix for all created resources.'

Resources:
  # Role para o AWS CodeBuild
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-CodeBuildRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-CodeBuildPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: '*' # Limitado ao bucket de artefatos pelo CodePipeline
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}-BuildProject:*'
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                Resource: '*' # Necessário para empacotar e implantar

  # Role para o AWS CloudFormation
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-CloudFormationRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-CloudFormationExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:*'
                  - 's3:*'
                  - 'dynamodb:*'
                  - 'lambda:*'
                  - 'sqs:*'
                  - 'events:*'
                  - 'ec2:*'
                  - 'ssm:*'
                  - 'logs:*'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteStack'
                Resource: '*' # Permissões amplas necessárias para o CFN gerenciar os recursos

  # Role para as Funções Lambda (Exemplo genérico, será refinado nas próximas fases)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-LambdaCustomPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: '*' # Será restringido ao bucket do projeto
              - Effect: Allow
                Action:
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource: '*' # Será restringido à tabela do projeto
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/trading_system/*'

Outputs:
  CodeBuildRoleArn:
    Description: 'ARN of the CodeBuild Role'
    Value: !GetAtt CodeBuildRole.Arn
  CloudFormationRoleArn:
    Description: 'ARN of the CloudFormation Role'
    Value: !GetAtt CloudFormationRole.Arn
  LambdaExecutionRoleArn:
    Description: 'ARN of the Lambda Execution Role'
    Value: !GetAtt LambdaExecutionRole.Arn
