AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Roles and Policies for the Crypto Trading System. StackName: crypto-trading-iam'

Parameters:
  ProjectName:
    Type: String
    Default: 'CryptoTradingSystem'
    Description: 'A prefix for all created resources.'
  ArtifactsBucketName:
    Type: String
    Description: 'Name of the S3 bucket for pipeline artifacts.'

Resources:
  # Role para o AWS CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-CodePipelineRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-CodePipelinePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: !Sub 'arn:aws:s3:::${ArtifactsBucketName}/*'
              - Effect: Allow
                Action:
                  - 'codestar-connections:UseConnection'
                Resource: '*' # A conexão é criada dinamicamente
              - Effect: Allow
                Action:
                  - 'codebuild:StartBuild'
                  - 'codebuild:BatchGetBuilds'
                Resource: '*' # O projeto de build é criado dinamicamente
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                Resource: '*'

  # Role para o AWS CodeBuild
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-CodeBuildRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-CodeBuildPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: !Sub 'arn:aws:s3:::${ArtifactsBucketName}/*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}-BuildProject:log-stream:*'
              - Effect: Allow
                Action:
                  - 'cloudformation:Package'
                Resource: '*'

  # Role para o AWS CloudFormation
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-CloudFormationRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-CloudFormationExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:*'
                  - 's3:*'
                  - 'dynamodb:*'
                  - 'lambda:*'
                  - 'sqs:*'
                  - 'events:*'
                  - 'scheduler:*'
                  - 'ec2:*'
                  - 'ssm:*'
                  - 'logs:*'
                Resource: '*'

  # Role para as Funções Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-LambdaCustomPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/trading_system/*'

Outputs:
  CodePipelineRoleArn:
    Description: 'ARN of the CodePipeline Role'
    Value: !GetAtt CodePipelineRole.Arn
  CodeBuildRoleArn:
    Description: 'ARN of the CodeBuild Role'
    Value: !GetAtt CodeBuildRole.Arn
  CloudFormationRoleArn:
    Description: 'ARN of the CloudFormation Role'
    Value: !GetAtt CloudFormationRole.Arn
  LambdaExecutionRoleArn:
    Description: 'ARN of the Lambda Execution Role'
    Value: !GetAtt LambdaExecutionRole.Arn
