AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation stack for the Crypto Trading System. It orchestrates all other nested stacks.'

Parameters:
  ProjectName:
    Type: String
    Default: 'CryptoTradingSystem'
    Description: 'A prefix for all created resources.'
  ArtifactsBucket:
    Type: String
    Description: 'S3 bucket for pipeline artifacts'
  CodeVersion:
    Type: String
    Description: 'Git commit hash for the code version'

Resources:

  # VPC
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './network.yaml'
      Parameters:
        ProjectName: !Ref ProjectName

  # Pilha de IAM
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './iam.yaml'
      Parameters:
        ProjectName: !Ref ProjectName

  # Pilha de Storage
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './storage.yaml'
      Parameters:
        ProjectName: !Ref ProjectName

  # Pilha de Processing
  ProcessingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './processing.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        LambdaExecutionRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        DataBucketName: !GetAtt StorageStack.Outputs.DataBucketName
        ArtifactsBucket: !Ref ArtifactsBucket  # Repassa o bucket de artefatos
        CodeVersion: !Ref CodeVersion
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        LambdaSecurityGroupId: !GetAtt NetworkStack.Outputs.LambdaSecurityGroupId
        SpotInstanceRoleArn: !GetAtt IAMStack.Outputs.SpotInstanceRoleArn
        SpotInstanceSecurityGroupId: !GetAtt NetworkStack.Outputs.SpotInstanceSecurityGroupId
    DependsOn:
      - IAMStack
      - StorageStack
      - NetworkStack


Outputs:
  DataBucketName:
    Description: 'S3 Bucket for data storage'
    Value: !GetAtt StorageStack.Outputs.DataBucketName
  StrategyTableName:
    Description: 'DynamoDB table for strategies'
    Value: !GetAtt StorageStack.Outputs.StrategyTableName
  ValidationQueueUrl:
    Description: 'URL of the SQS validation queue'
    Value: !GetAtt ProcessingStack.Outputs.ValidationQueueUrl
  DataDownloaderFunctionArn:
    Description: 'ARN of the data downloader Lambda function'
    Value: !GetAtt ProcessingStack.Outputs.DataDownloaderFunctionArn
  DataDownloaderFunctionName:
    Description: 'Name of the data downloader Lambda function'
    Value: !GetAtt ProcessingStack.Outputs.DataDownloaderFunctionName