AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation stack for the Crypto Trading System. It orchestrates all other nested stacks.'

Parameters:
  ProjectName:
    Type: String
    Default: 'CryptoTradingSystem'
    Description: 'A prefix for all created resources.'
  # Parâmetros que serão passados para a pilha do pipeline
  GitHubOwner:
    Type: String
    Description: 'Your GitHub username or organization name.'
  GitHubRepo:
    Type: String
    Description: 'The name of the GitHub repository.'
  ArtifactsBucket:
    Type: String
    Description: 'S3 bucket for pipeline artifacts.'

Resources:
  # Pilha de IAM (criada primeiro)
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './iam.yaml'
      Parameters:
        ProjectName: !Ref ProjectName

  # Pilha do Pipeline (agora também é uma pilha aninhada)
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './pipeline.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        ArtifactsBucket: !Ref ArtifactsBucket
        # Passando os ARNs das roles criadas na IAMStack
        CodeBuildRoleArn: !GetAtt IAMStack.Outputs.CodeBuildRoleArn
        CloudFormationRoleArn: !GetAtt IAMStack.Outputs.CloudFormationRoleArn
        CodePipelineRoleArn: !GetAtt IAMStack.Outputs.CodePipelineRoleArn # Adicionamos esta role também
    DependsOn:
      - IAMStack

  # Pilha de Storage
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './storage.yaml'
      Parameters:
        ProjectName: !Ref ProjectName

  # Pilha de Processing
  ProcessingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './processing.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        LambdaExecutionRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
    DependsOn:
      - IAMStack
      - StorageStack

Outputs:
  PipelineName:
    Description: 'Name of the CodePipeline'
    Value: !GetAtt PipelineStack.Outputs.PipelineName
  DataBucketName:
    Description: 'S3 Bucket for data storage'
    Value: !GetAtt StorageStack.Outputs.DataBucketName
  StrategyTableName:
    Description: 'DynamoDB table for strategies'
    Value: !GetAtt StorageStack.Outputs.StrategyTableName
