# infra/network.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cria os recursos de rede (VPC, Subnets, Security Groups). Atualmente um placeholder para futuras expansões.'

Parameters:
  ProjectName:
    Type: String
    Default: 'CryptoTradingSystem'

Resources:
  # Por enquanto, não há recursos de rede personalizados necessários.
  # As Lambdas e a EC2 Spot podem operar na VPC padrão.
  # Este template está aqui para estruturar o projeto e permitir expansões futuras,
  # como a criação de uma VPC dedicada com sub-redes públicas e privadas.

  TradingSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-SG'
      GroupDescription: 'Security Group para recursos do sistema de trading'
      VpcId:
        Fn::ImportValue:
          !Sub "${AWS::StackName}-VPCID" # Exemplo se tivéssemos uma VPC dedicada
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  SecurityGroupId:
    Description: "ID do Security Group principal"
    Value: !Ref TradingSecurityGroup
    Export:
      Name: !Sub '${ProjectName}-SecurityGroupId'
